services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPass
      POSTGRES_DB: cs2
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - cs25v5-network

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgresUser:postgresPass@db:5432/cs2
      PORT: 4000
      NODE_ENV: production
      HOST_BACKEND_PORT: ${HOST_BACKEND_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "${HOST_BACKEND_PORT}:4000"
    # SIN volumes aquí
    command: npm run start
    networks:
      - cs25v5-network

  frontend:
    build: ./frontend
    # Pass API base to Vite at build time
    build:
      context: ./frontend
      args:
        VITE_API_BASE: ${VITE_API_BASE}
    depends_on:
      - backend
    ports:
      - "${HOST_FRONTEND_PORT}:3000"
    # Static serving of built assets
    networks:
      - cs25v5-network

volumes:
  db-data:
networks:
  cs25v5-network:
    driver: bridge